"""add_trip_shares_table

Revision ID: 2543f944e06a
Revises: 72877339351e
Create Date: 2025-12-13 12:38:42.209860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2543f944e06a'
down_revision = '72877339351e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_shares',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('shared_with_email', sa.String(length=255), nullable=False),
    sa.Column('shared_with_user_id', sa.UUID(), nullable=True),
    sa.Column('permission', sa.String(length=10), nullable=False),
    sa.Column('invite_code', sa.String(length=50), nullable=False),
    sa.Column('invite_expires_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shared_with_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_code')
    )
    op.create_index(op.f('ix_trip_shares_owner_id'), 'trip_shares', ['owner_id'], unique=False)
    op.create_index(op.f('ix_trip_shares_shared_with_user_id'), 'trip_shares', ['shared_with_user_id'], unique=False)
    op.create_index(op.f('ix_trip_shares_trip_id'), 'trip_shares', ['trip_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trip_shares_trip_id'), table_name='trip_shares')
    op.drop_index(op.f('ix_trip_shares_shared_with_user_id'), table_name='trip_shares')
    op.drop_index(op.f('ix_trip_shares_owner_id'), table_name='trip_shares')
    op.drop_table('trip_shares')
    # ### end Alembic commands ###
