"""add google auth fields to users

Revision ID: 60cec025285a
Revises: fefe1ca604e4
Create Date: 2025-12-13 16:33:59.281173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60cec025285a'
down_revision = 'fefe1ca604e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firebase_uid', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('google_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('display_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('photo_url', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('last_login', sa.DateTime(), nullable=True))

    # Add auth_provider with default value for existing users
    op.add_column('users', sa.Column('auth_provider', sa.String(length=50), nullable=True))
    op.execute("UPDATE users SET auth_provider = 'email' WHERE auth_provider IS NULL")
    op.alter_column('users', 'auth_provider', nullable=False)

    # Add email_verified with default value for existing users
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET email_verified = FALSE WHERE email_verified IS NULL")
    op.alter_column('users', 'email_verified', nullable=False)

    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'photo_url')
    op.drop_column('users', 'display_name')
    op.drop_column('users', 'google_id')
    op.drop_column('users', 'auth_provider')
    op.drop_column('users', 'firebase_uid')
    # ### end Alembic commands ###
