"""add_weather_and_currency_tables

Revision ID: 6ba8c554f9c4
Revises: 2050709e87bd
Create Date: 2025-12-13 14:00:07.685964

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6ba8c554f9c4'
down_revision = '2050709e87bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('rates', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base_currency')
    )
    op.create_index('ix_exchange_rates_base', 'exchange_rates', ['base_currency'], unique=False)
    op.create_index('ix_exchange_rates_expires', 'exchange_rates', ['expires_at'], unique=False)
    op.create_table('supported_currencies',
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('flag_emoji', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('weather_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=False),
    sa.Column('location_name', sa.String(length=255), nullable=True),
    sa.Column('country_code', sa.String(length=3), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('weather_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_weather_cache_expires', 'weather_cache', ['expires_at'], unique=False)
    op.create_index('ix_weather_cache_location_date', 'weather_cache', ['latitude', 'longitude', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_weather_cache_location_date', table_name='weather_cache')
    op.drop_index('ix_weather_cache_expires', table_name='weather_cache')
    op.drop_table('weather_cache')
    op.drop_table('supported_currencies')
    op.drop_index('ix_exchange_rates_expires', table_name='exchange_rates')
    op.drop_index('ix_exchange_rates_base', table_name='exchange_rates')
    op.drop_table('exchange_rates')
    # ### end Alembic commands ###
